export class Agent
{
    constructor(
        public first_name:string,
        public last_name:string,
        public is_agent:boolean,
        public is_manager:boolean,
        public password:string,
        public password2:string,
        public gender:string,
        public profile_image:string,
        public nic_number:string,
        public phone_number:string,
        public location:string,        
        )
    {

    }
}