export class Applicant
{
    constructor(
        public first_name:string,
        public  last_name:string,
        public  gender:string,
        public nic_image:string,
        public phone_number :string,
        public  wave_phone_number:string,
        public email:string,
        public   profession:string,
        public  revenue:string,
        public   profile:string,
        public   business_line:string,
        public created_date:string,
        public id:number,
        public  location: any,
        
        
    )
    {

    }
}